### ISSUE TITLE
model_path without root_dir doesn't work.

### ISSUE THREAD

**Issue by Gldkslfmsd** [backspacetg/simul_whisper#6]
I did the following changes: I set `model_path="base"` and it crashed because the path does not start with `./` or it's is not absolute path.

```
(p3) machacek@tdll-8gpu3:~/work/smluvni-2024/alignatt-whisper.202412/simul_whisper$ git diff transcribe.py 
diff --git a/transcribe.py b/transcribe.py
index ac6aab8..de88973 100644
--- a/transcribe.py
+++ b/transcribe.py
@@ -7,8 +7,8 @@ from simul_whisper.transcriber.config import AlignAttConfig
 from simul_whisper.transcriber.segment_loader import SegmentWrapper
 from simul_whisper.transcriber.simul_whisper import PaddedAlignAttWhisper, DEC_PAD
 
-model_path = "path-to-the-whisper-checkpoint"
-if_ckpt_path = "cif_models/small.pt" # align with the whisper model. e.g., using small.pt for whisper small
+model_path = "base"
+if_ckpt_path = "cif_models/base.pt" # align with the whisper model. e.g., using small.pt for whisper small
 
 segment_length = 1.0 # chunk length, in seconds
 frame_threshold = 12 # threshold for the attention-guided decoding, in frames
@@ -16,7 +16,7 @@ buffer_len = 20 # the lengths for the context buffer, in seconds
 min_seg_len = 0.0 # transcibe only when the context buffer is larger than this threshold. Useful when the segment_length is small
 language = "en"
 
-audio_path = "path-to-the-audio-file"
+audio_path = "sample.wav"
```

```
(p3) machacek@tdll-8gpu3:~/work/smluvni-2024/alignatt-whisper.202412/simul_whisper$ python3 transcribe.py 
Traceback (most recent call last):
  File "/simul_whisper/transcribe.py", line 33, in <module>
    model = PaddedAlignAttWhisper(cfg)
  File "/simul_whisper/simul_whisper/transcriber/simul_whisper.py", line 22, in __init__
    self.model = load_model(name=model_name, download_root=model_path)
  File "/simul_whisper/simul_whisper/whisper/__init__.py", line 131, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/simul_whisper/simul_whisper/whisper/__init__.py", line 49, in _download
    os.makedirs(root, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

Proposed solution: document the need for / in path, or use os.path, or something else.

Thanks!

**Comment by Gldkslfmsd** [comment]
Hi, @backspacetg , 
FYI: I fixed this issue here: https://github.com/ufal/SimulStreaming/commit/8442860619f388bbcc9228ed63a27affee761e45#diff-7a122320bd733b07cc291d927b86671de50b9a00d116e2af9e0301f0cc63e133R34
. It's in SimulStreaming, my new project where I merged your SimulWhisper with WhisperStreaming and extended them. I hope you'll like it.

**Comment by backspacetg** [comment]
I'm glad to see that, and congratulations on your impressive result at IWSLT 2025!

**Comment by Gldkslfmsd** [comment]
Thanks! And thank you for releasing simul_whisper, it is an important work I followed up.
